In [66]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1LGIqg-K8-oefXU2OzT0Pi_vXXV7VmYN5')

## Name : Sudhakar Anemu (sudhakar.anemu@gmail.com)
### Assignment Two

> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: <br>https://numpy.org/doc/stable/reference/routines.html 

> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: **TODO - INSERT SUBMISSION LINK**
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- append
- column_slack
- dot
- flip
- max

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [67]:
!pip install jovian --upgrade -q

In [68]:
import jovian

In [69]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/sudhakar-anemu/numpy-array-operations


'https://jovian.ml/sudhakar-anemu/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [70]:
import numpy as np

In [71]:
# List of functions explained 
function1 = np.append
function2 = np.column_stack
function3 = np.dot
function4 = np.flip
function5 = np.max

## Function 1 - np.append

Append array to the end of the Array. 
<br> Syntex : append(arr, values, axis=None)

In [72]:
arr2by3 = np.array([[1,2,3], [4,5,6]])
print("Array : arr2by3 : \n", arr2by3)

arr1by3 = np.array([[7,8,9]])
print("Array : arr1by3 : \n", arr1by3)

print("Appending both arrays  : \n", np.append(arr2by3, arr1by3))

Array : arr2by3 : 
 [[1 2 3]
 [4 5 6]]
Array : arr1by3 : 
 [[7 8 9]]
Appending both arrays  : 
 [1 2 3 4 5 6 7 8 9]


Here we verified the append function with a 2*3 and 1*3 matrix with out mentioning the axis. Then it returns the 1*9 Matrix

In [73]:
print("Appending both arrays  : \n", np.append(arr2by3, arr1by3, axis = 0))

Appending both arrays  : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Here we verified the append function with a 2 * 3 and 1 * 3 matrix with mentioning the axis=0. Then it returns the 3 * 3 matrix.

In [74]:
print("Appending both arrays  : \n", np.append(arr2by3, arr1by3, axis = 1))

ValueError: ignored

Here we tried with the axix=1, It returns an error since the mismatch of the dimentions.

In [ ]:
jovian.commit()

## Function 2 - np.column_stack

Stack 1-D arrays as columns into a 2-D array. Take a sequence of 1-D arry and stack them as columns to make a singel 2-D array. 2-D arrays are stacked as-is.

In [ ]:
# Example 1 - working
arr1by3 = np.array([1,2,3])
print("Type of arr1by3 : ", type(arr1by3), "\nContent : arr1by3 : ", arr1by3)

arr11by3 = np.array([4,5,6])
print("Type of arr11by3 : ", type(arr11by3), "\nContent : arr11by3 : ", arr11by3)

fin3by2 = np.column_stack((arr1by3, arr11by3))
print("Final array after the stack : \n", fin3by2)

Here we gave two single dimentional arrays as input which returns 3by2 dimentianl arrays.

In [ ]:
# Example 2 - working
arr2by3 = np.array([[1,2,3], [4,5,6]])
print("Type of arr2by3 : \n", type(arr2by3), "\nContent : arr1by3 : \n", arr2by3)

arr22by3 = np.array([[7,8,9], [10,11,12]])
print("Type of arr22by3 : \n", type(arr22by3), "\nContent : arr11by3 : \n", arr22by3)

fin3by2 = np.column_stack((arr2by3, arr22by3))
print("Final array after the stack : \n", fin3by2)

Here we have given two 2 by 3 arrays as input to the stack, which returns 2 by 6 array with out any errors.

In [75]:
# Example 3 - breaking (to illustrate when it breaks)
arr1by3 = np.array([1,2,3])
print("Type of arr1by3 : ", type(arr1by3), "\nContent : arr1by3 : ", arr1by3)

arr2by3 = np.array([[1,2,3], [4,5,6]])
print("Type of arr2by3 : \n", type(arr2by3), "\nContent : arr1by3 : \n", arr2by3)

finall = np.column_stack((arr1by3, arr2by3))
print("Final array after the stack : \n", finall)

Type of arr1by3 :  <class 'numpy.ndarray'> 
Content : arr1by3 :  [1 2 3]
Type of arr2by3 : 
 <class 'numpy.ndarray'> 
Content : arr1by3 : 
 [[1 2 3]
 [4 5 6]]


ValueError: ignored

Here we tried to give 1 by 3 and 2 by 3 arrays as input where it returns an error since the mismatch of the Dimension.<br>This issue was fixed in the example 2

In [ ]:
jovian.commit()

## Function 3 - np.dot

Dot product of two arrays. Here a and b are arrays :
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.

In [ ]:
# Example 1 - working
arr1by3 = np.array([1,2,3])
print("Type of arr1by3 : ", type(arr1by3), "\nContent : arr1by3 : ", arr1by3)

arr11by3 = np.array([4,5,6])
print("Type of arr11by3 : ", type(arr11by3), "\nContent : arr11by3 : ", arr11by3)

fin3by2 = np.dot(arr1by3, arr11by3)
print("Final value after the dot of both arrays : \n", fin3by2)

Here we have given 1by3 1,2,3 and 1by3 4,5,6 are inputs to the dot which returns 32 (1*4 + 2*5 + 3*6) = 4+10+18.

In [ ]:
# Example 2 - working
arr2by2 = np.array([[1,2], [3,4]])
print("Type of arr2by3 : \n", type(arr2by2), "\nContent : arr1by3 : \n", arr2by2)

arr22by2 = np.array([[5,6], [7,8]])
print("Type of arr22by3 : \n", type(arr22by2), "\nContent : arr11by3 : \n", arr22by2)

fin3by2 = np.dot(arr2by3, arr22by2)
print("Final array after the stack : \n", fin3by2)

Here we multiplied two 2by2 arrays which returns 2by2 with the multiplication of each values respectively. 

In [76]:
# Example 3 - breaking (to illustrate when it breaks)
arr1by3 = np.array([1,2,3])
print("Type of arr1by3 : ", type(arr1by3), "\nContent : arr1by3 : ", arr1by3)

arr2by3 = np.array([[1,2,3], [4,5,6]])
print("Type of arr2by3 : \n", type(arr2by3), "\nContent : arr1by3 : \n", arr2by3)

finall = np.dot(arr1by3, arr2by3)
print("Final value after the dot : \n", finall)

Type of arr1by3 :  <class 'numpy.ndarray'> 
Content : arr1by3 :  [1 2 3]
Type of arr2by3 : 
 <class 'numpy.ndarray'> 
Content : arr1by3 : 
 [[1 2 3]
 [4 5 6]]


ValueError: ignored

Here, we tried to multiply two different arrays(one is 1by3 and another one is 2by3 arrays). Which returns an error when we do dot since there is difference in the dimension.<br>This issue was fixed in the example 2

In [ ]:
jovian.commit()

## Function 4 : np.flip

  Reverse the order of elements in an array along the given axis. The shape of the arrray is preserved, but the elements are reordered.

In [ ]:
# Example 1 - working
arr3by3 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("Type of the array : \n", type(arr3by3))
print("Content of this array : \n", arr3by3)
print("Array after flipping by 1 : \n\n", np.flip(arr3by3,1))

Here we re-order the 3 by 3 matrix by 3 by 3 but the placemen of values are different positions by using the flip function.

In [ ]:
# Example 2 - working
arr3by31 = np.array([[[0, 1],
            [2, 3]],
           [[4, 5],
            [6, 7]]])
print("Content of this array : \n", arr3by31)

print("Array after flipping by 2\n\n", np.flip(arr3by31,2))

Here we re-order the two 2 by 2 matrixes by the axis 2 which returns the same but the position of the numbers are different.

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
arr3by31 = np.array([[[0, 1],
            [2, 3]],
           [[4, 5],
            [6, 7]]])
print("Content of this array : \n", arr3by31)

print("Array after flipping by 2\n\n", np.flip(arr3by31,4))

Tried the same matrix by giving 4 at the flip function, but it fails due to the out of bound error. <br>This issue was fixed in the example 2

In [ ]:
jovian.commit()

## Function 5 : np.max

It return the maximum of an array or maximum along an axis.

In [ ]:
# Example 1 - working
arr2by3 = np.array([[1,2,3], [4,5,6]])
print("Type of arr2by3 : \n", type(arr2by3), "\nContent : arr1by3 : \n", arr2by3)

print("Max of the Matrix (arr2by3) is : ", np.max(arr2by3))

Captured a max value of an array 2 by 3, which has values  1 2 3 and 4 5 6. it returns 6 since it is the max value.

In [ ]:
# Example 2 - working
print("Max of the Matrix (arr2by3) is : ", np.max(arr2by3, 1))

For the same Matrix, it returns  3 6 since the axis is 1. 

In [77]:
# Example 3 - breaking (to illustrate when it breaks)
print("Max of the Matrix (arr2by3) is : ", np.max(arr2by3, 3))

AxisError: ignored

For the same Matrix, it returns an error since the dimention is out of bound.<br>This issue was fixed in the example2

In [ ]:
jovian.commit()

## Conclusion

Numpy is most useful package which has huge number of functions. Which are very useful in the Datascience. 

Tried different options of below modules and noted in the above notes.
- append
- column_slack
- dot
- flip
- max

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* https://numpy.org/doc/stable/reference/routines.html 

In [ ]:
jovian.commit()